# Generated by Django 5.2.8 on 2025-11-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='login',
        ),
    ]
